spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javarush_tracker
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    operations-sorter: alpha # Делает так, чтобы методы в интерфейсе были отсортированы по алфавиту (GET, POST...)
    path: /swagger           # Позволяет заходить на документацию по удобному короткому адресу /swagger
  api-docs:
    path: /v3/api-docs       # Путь, куда Спринг выплюнет сырой JSON со всеми эндпоинтами